services:
  mongo:
    image: mongo
    container_name: btgpactual-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672" # web -> login: guest pass:guest
      - "5672:5672"
