services:
  mysql-dev:
    image: mysql:8.0
    container_name: borrow-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: borrow-api
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3308:3306"
